import colors

FPS = 30
WIDTH = 840
HEIGHT = 620
SIZE = (WIDTH, HEIGHT)
FONT_SIZE = 40
CELL_WIDTH = 25
CELL_HEIGHT = 25
CELL_SIZE = (CELL_WIDTH, CELL_HEIGHT)
DEFAULT_BACKGROUND_COLOR = colors.BW_GREY
SAND_BACKGROUND_COLOR = colors.SAND
DEFAULT_SYMBOL_COLOR = colors.WHITE
ANTIALIAS = True
# DEFAULT_FONT = pygame.font.Font(None, FONT_SIZE)