# -*- coding: utf-8 -*-

FPS = 30
MAP_WIDTH = 1920
MAP_HEIGHT = 800
SCREEN_SIZE = (MAP_WIDTH, MAP_HEIGHT)
FONT_SIZE = 30
CELL_WIDTH = 64
CELL_HEIGHT = 64
CELL_SIZE = (CELL_WIDTH, CELL_HEIGHT)
ANTIALIAS = True
